name: CUPS-AVAHI-AIRPRINT Server
version: "2.2.0"
stage: experimental
slug: cups
description: A CUPS print server
url: https://github.com/lkadar2015/hass-add-ons/
arch:
  - amd64
usb: true
init: false
homeassistant_api: true
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: For other devices on the local network to print to this server
  631/udp: For other devices on the local network to print to this server
map:
  - ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  require_ssl: true
schema:
  ssl: bool
  cafile: str?
  certfile: str
  keyfile: str
  require_ssl: bool
