name: "OSCam"
description: "OSCam add on"
version: "1.1.0"
slug: "OSCam"
image: lscr.io/linuxserver/oscam:latest
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8888/tcp: 8888
options:
schema:
